
# I copied the pyproj file from Laurane's fork for
# this and then added two lines at the bottom for tests


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ticoi"
version = "0.0.1"
authors = [
  { name="Laurane Charrier", email="laurane.charrier@outlook.com" },{ name="Lei Guo"}
]
description = "A package to run an Temporal Inversion based on the temporal ClOsure of the measurement network, and Interpolation (TICOI)"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/ticoi/ticoi.git"
Issues = "https://github.com/pypa/sampleproject/issues"

[tool.pytest.ini_options]
testpaths = "."

[tool.setuptools.packages.find]
where = ["."]
include = ["ticoi"]
exclude = []
namespaces= false

